services:
  - type: web
    name: spice-website
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn spice_site.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHON_VERSION
        value: "3.10.12"
